import type { Config } from "tailwindcss";

import tailwindcss_animate from "tailwindcss-animate";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    padding: {
      xxxs: "2px",
      xxs: "4px",
      xs: "8px",
      sm: "10px",
      md: "12px",
      lg: "16px",
      xl: "20px",
      xxl: "24px",
      xxxl: "32px",
    },
    margin: {
      xxxs: "2px",
      xxs: "4px",
      xs: "8px",
      sm: "10px",
      md: "12px",
      lg: "16px",
      xl: "20px",
      xxl: "24px",
      xxxl: "32px",
    },
    gap: {
      xxxs: "4px",
      xxs: "6px",
      xs: "8px",
      sm: "12px",
      md: "16px",
      lg: "20px",
      xl: "24px",
      xxl: "28px",
      xxxl: "32px",
    },

    borderRadius: {
      xxxs: "1px",
      xxs: "2px",
      xs: "3px",
      sm: "4px",
      md: "6px",
      lg: "8px",
      xl: "10px",
      xxl: "12px",
      xxxl: "14px",
    },

    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        brand: {
          50: "var(--palette-brand-50)",
          100: "var(--palette-brand-100)",
          200: "var(--palette-brand-200)",
          300: "var(--palette-brand-300)",
          400: "var(--palette-brand-400)",
          500: "var(--palette-brand-500)",
          600: "var(--palette-brand-600)",
          700: "var(--palette-brand-700)",
          800: "var(--palette-brand-800)",
          900: "var(--palette-brand-900)",
          950: "var(--palette-brand-950)",
        },
        success: {
          50: "var(--palette-success-50)",
          100: "var(--palette-success-100)",
          200: "var(--palette-success-200)",
          300: "var(--palette-success-300)",
          400: "var(--palette-success-400)",
          500: "var(--palette-success-500)",
          600: "var(--palette-success-600)",
          700: "var(--palette-success-700)",
          800: "var(--palette-success-800)",
          900: "var(--palette-success-900)",
          950: "var(--palette-success-950)",
        },
        warning: {
          50: "var(--palette-warning-50)",
          100: "var(--palette-warning-100)",
          200: "var(--palette-warning-200)",
          300: "var(--palette-warning-300)",
          400: "var(--palette-warning-400)",
          500: "var(--palette-warning-500)",
          600: "var(--palette-warning-600)",
          700: "var(--palette-warning-700)",
          800: "var(--palette-warning-800)",
          900: "var(--palette-warning-900)",
          950: "var(--palette-warning-950)",
        },
        error: {
          50: "var(--palette-error-50)",
          100: "var(--palette-error-100)",
          200: "var(--palette-error-200)",
          300: "var(--palette-error-300)",
          400: "var(--palette-error-400)",
          500: "var(--palette-error-500)",
          600: "var(--palette-error-600)",
          700: "var(--palette-error-700)",
          800: "var(--palette-error-800)",
          900: "var(--palette-error-900)",
          950: "var(--palette-error-950)",
        },
        neutral: {
          50: "var(--palette-neutral-50)",
          100: "var(--palette-neutral-100)",
          200: "var(--palette-neutral-200)",
          300: "var(--palette-neutral-300)",
          400: "var(--palette-neutral-400)",
          500: "var(--palette-neutral-500)",
          600: "var(--palette-neutral-600)",
          700: "var(--palette-neutral-700)",
          800: "var(--palette-neutral-800)",
          900: "var(--palette-neutral-900)",
          950: "var(--palette-neutral-950)",
        },
      },
      backgroundColor: {
        // todo: fill these values correctly
        brand: {
          primary: "var(--palette-brand-700)",
          secondary: "var(--palette-brand-500)",
          tertiary: "var(--palette-brand-300)",
          quaternary: "var(--palette-brand-200)",
        },
        neutral: {
          primary: "var(--palette-neutral-700)",
          secondary: "var(--palette-neutral-600)",
          tertiary: "var(--palette-neutral-300)",
          quaternary: "var(--palette-neutral-200)",
        },
        success: {
          primary: "var(--palette-success-700)",
          secondary: "var(--palette-success-600)",
          tertiary: "var(--palette-success-300)",
          quaternary: "var(--palette-success-200)",
        },
        warning: {
          primary: "var(--palette-warning-700)",
          secondary: "var(--palette-warning-600)",
          tertiary: "var(--palette-warning-300)",
          quaternary: "var(--palette-warning-200)",
        },
        error: {
          primary: "var(--palette-error-700)",
          secondary: "var(--palette-error-600)",
          tertiary: "var(--palette-error-300)",
          quaternary: "var(--palette-error-200)",
        },
      },
      textColor: {
        // todo: fill these values correctly
        brand: {
          primary: "var(--palette-brand-800)",
          secondary: "var(--palette-brand-600)",
          tertiary: "var(--palette-brand-400)",
          quaternary: "var(--palette-brand-200)",
        },
        neutral: {
          primary: "var(--palette-neutral-800)",
          secondary: "var(--palette-neutral-600)",
          tertiary: "var(--palette-neutral-400)",
          quaternary: "var(--palette-neutral-200)",
        },
        success: {
          primary: "var(--palette-success-800)",
          secondary: "var(--palette-success-600)",
          tertiary: "var(--palette-success-400)",
          quaternary: "var(--palette-success-200)",
        },
        warning: {
          primary: "var(--palette-warning-800)",
          secondary: "var(--palette-warning-600)",
          tertiary: "var(--palette-warning-400)",
          quaternary: "var(--palette-warning-200)",
        },
        error: {
          primary: "var(--palette-error-800)",
          secondary: "var(--palette-error-600)",
          tertiary: "var(--palette-error-400)",
          quaternary: "var(--palette-error-200)",
        },
      },
      borderColor: {
        // todo: fill these values correctly
        brand: {
          primary: "var(--palette-brand-700)",
          secondary: "var(--palette-brand-500)",
          tertiary: "var(--palette-brand-300)",
          quaternary: "var(--palette-brand-200)",
        },
        neutral: {
          primary: "var(--palette-neutral-700)",
          secondary: "var(--palette-neutral-500)",
          tertiary: "var(--palette-neutral-300)",
          quaternary: "var(--palette-neutral-200)",
        },
        success: {
          primary: "var(--palette-success-700)",
          secondary: "var(--palette-success-500)",
          tertiary: "var(--palette-success-300)",
          quaternary: "var(--palette-success-200)",
        },
        warning: {
          primary: "var(--palette-warning-700)",
          secondary: "var(--palette-warning-500)",
          tertiary: "var(--palette-warning-300)",
          quaternary: "var(--palette-warning-200)",
        },
        error: {
          primary: "var(--palette-error-700)",
          secondary: "var(--palette-error-500)",
          tertiary: "var(--palette-error-300)",
          quaternary: "var(--palette-error-200)",
        },
      },
    },
  },
  plugins: [tailwindcss_animate],
};
export default config;
